version: "3"
services:
  hdfs:
    image: osipmd/hdfs
    container_name: hdfs
    hostname: hdfs
    ports:
      - "8088:8088"
      - "9000:9000"
      - "50070:50070"
      - "50075:50075"
      - "50030:50030"
      - "50060:50060"
  spark-master:
    image: osipmd/spark-master
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: osipmd/spark-worker
    container_name: spark-worker
    hostname: spark-worker
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"